version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - '5001:5000'  # Change this line
    environment:
      - MONGODB_URI=mongodb+srv://user-123:Papa7758$$@clusterreps.w6x6iki.mongodb.net/?retryWrites=true&w=majority&appName=ClusterReps
  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
